# Generated by Django 4.2.5 on 2023-09-25 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='characteristics',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='TypeCharacteristic',
        ),
        migrations.AddField(
            model_name='item',
            name='gear',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.gear'),
            preserve_default=False,
        ),
    ]
