# Generated by Django 4.2.5 on 2023-09-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='characteristics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.typecharacteristic'),
        ),
    ]
