# Generated by Django 4.2.5 on 2023-09-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_gear_remove_item_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cover',
            field=models.ImageField(default=3, upload_to='coverGear/'),
            preserve_default=False,
        ),
    ]
