# Generated by Django 4.2.5 on 2023-09-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
