# Generated by Django 4.2.5 on 2023-09-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_item_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cover',
        ),
        migrations.AddField(
            model_name='gear',
            name='cover',
            field=models.ImageField(default=0, upload_to='coverGear/'),
            preserve_default=False,
        ),
    ]
