# Generated by Django 4.2.7 on 2023-11-23 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_server_cover_gear_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20)),
                ('estagio', models.CharField(choices=[('negociacao', 'Negociação'), ('pagamento', 'Pagamento'), ('entrega', 'Entrega')], default='negociacao', max_length=20)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_como_comprador', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_como_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('itens', models.ManyToManyField(to='account.item')),
            ],
        ),
    ]
