# Generated by Django 4.2.7 on 2023-11-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_conjunto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='descricao',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
